###
- hosts: vcenter
  become: yes

  roles:
    - {role: create-snap-vcenter, tags: ['create', 'pre-task']}
    - {role: restore-snap-vcenter, tags: ['restore', 'pre-task']}
    - {role: restore-snap-last-vcenter, tags: ['restore-last', 'pre-task']}

